### ISSUE TITLE
Texify Benchmark Figure

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy-articles#179]
This is a dummy issue to ask the opinion of everyone. It is completely OK for me if we close it without merging. It is also nice for quick archiving for later. I was exceptionally busy this week so couldn't keep my promise to @mdhaber but it's late then never I guess.

<hr>

Here is the Texified figure using the data in CSV format for the benchmark figure about 100kB in total.

![image](https://user-images.githubusercontent.com/1303842/60744966-90752900-9f78-11e9-9f5d-a3b56586ff15.png)

obtained via 

```latex
\begin{tikzpicture}
\begin{axis}[
    ymode=log,
    width=14cm, height=5cm,
    date coordinates in=x,
    xticklabel={\year},
    xtick={2009-01-01 00:00,
           2010-01-01 00:00,
           20...-01-01 00:00,
           2017-01-01 00:00},
    xmin=2008-01-01 00:00,
    xmax=2018-06-01 00:00,
    ymin=0.001, ymax=1,
    log ticks with fixed point,
    grid=both,grid style={line width=0.25pt, gray!20},
    xlabel={Commit Date},
    ylabel={Execution Time (s)},
    legend entries={$m=3$, $m=8$, $m=16$}, legend cell align=left, legend pos=outer north east,
    extra x ticks={2008-11-10 17:49:08,2012-08-27 00:00,2015-05-15 17:20:07,2017-10-16 20:28:24},
    extra x tick style={grid=major,grid style={line width=1pt, gray!50, dashed},
                        ticklabel pos=top,align=center, text depth=1ex},
    extra x tick labels={{\texttt{cKdTree}\\introduced},
                         {\texttt{cKdTree} Fully\\Cythonized},
                         {\texttt{cKdTree}\\rewritten in C++},
                         {Scipy 1.0\\released}}
    ]
    \pgfplotsinvokeforeach{0,1,2} {
        \pgfplotstableread[col sep=semicolon]{static/csvout0#1.txt}\table
        \addplot+[only marks, mark=*,mark options={draw=none, mark size=1pt}]
            table[x=date,y=value] {\table};
    }

\end{axis}
\end{tikzpicture}
```

This needs the additional line `\usepgfplotslibrary{dateplot}` in the preamble somewhere after `pgfplotstable` package is loaded. 

The following files need to be added under static 

[csvout01.txt](https://github.com/scipy/scipy-articles/files/3363989/csvout01.txt)
[csvout02.txt](https://github.com/scipy/scipy-articles/files/3363990/csvout02.txt)
[csvout00.txt](https://github.com/scipy/scipy-articles/files/3363991/csvout00.txt)

**Comment by ilayn** [comment]
@mdhaber If you want this in please let me know and I can make a PR.

**Comment by MartinThoma** [comment]
I was about to do the same :smile: 

What about removing the box around m=3, m=8, m=16?

**Comment by mdhaber** [comment]
@ilayn Thanks for your patience.

On one hand, a TeX-defined figure is easier to maintain - but only for those who know what they're doing. I know we have an enriched population of TeX-savvy people, but I only just get by, and Inkscape is easier for me. 

Also, I spent some time improving the figure from the original screenshot to the version that is currently in the paper, and consequently I find the version in the paper more pleasing than this one. I guess I can't help it. I think I have some objective points - this needs an x-axis label, consistent capitalization of the annotations, addition of a label for 2018, and the removal of certain data points as we discussed in one of these issues. There are also some subjective ones - I prefer the current version's colors, annotation locations and indicators, and legend placement; for whatever reason it looks more interesting to me. I'm sure all of these are easily changed. But since I've already put in the to make the original, I'm not really eager to go through reviewing all that unless there a strong case (not based on the axiom that TeX is better).

So I can't vote in favor of this change, yet. But I'll stay out of the way, and if we can make this TeXify'd version [outstanding](https://informationisbeautiful.net/2019/winners-of-the-world-data-visualization-prize/), I'd be all about it. 

(Hope I'm being reasonable : / I appreciate the time you put into this and all your other help on the paper.)

**Comment by ilayn** [comment]
No problem at all Matt. Consider this as an archived version. It was kind of too large for the data files to store for a figure. Also I didn't spend more than 30 minutes so no worries 😊

If we need it, it is here. Polishing it further also takes equal time
