### ISSUE TITLE
Comment to Address: Future of SciPy / GPU/ distributed ecosystem

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#220]
I think @mdhaber will go ahead and add the majority of the reviewer comments from *Nature Methods* in **anonymous** fashion for the community to help address, as separate issues. Here's a first set of comments to address, grouped together because they are similar requests that we've been specifically asked to address by the Editors.

Reviewer 1:

> I would like a longer discussion about the future of SciPy particularly SciPy’s lack of the two features that are starting to become understood as essential to scientific computing: built-in automatic reverse-mode differentiation and heterogenous computation (e.g. CPU, DSP, GPU, etc.). Will SciPy adapt to support these increasingly vital features? Is it even possible without a substantial rewrite?

Reviewer 2:

> Distributed and GPU is considered out of scope but is conversely is believed to be required in the future for data and scientific analysis. A discussion of alternatives and how you interact with other ecosystems should be considered (e.g., RAPIDS, Dask, etc). How does SciPy progress with the rapidly evolving hardware?

**Comment by rgommers** [comment]
I think the question is what to write down about this, because it's not all decided yet. But in principle we do have some answers here:

- http://scipy.github.io/devdocs/roadmap.html#support-for-distributed-arrays-and-gpu-arrays (needs an update, but it's been on our roadmap for a little while)
- We now have a backend system in scipy.fft that allows calling SciPy functions and have them execute on GPU (via CuPy), GPU (via Dask) and even on a multi-GPU system (via Dask + CuPy). This can be extended to most other modules in a straightforward manner (`linalg` and `special` will be high on the list). It of course only makes sense to do so if there are alternative implementation available or in the works.
- Automatic differentiation: this was only a nitpick of the first reviewer, and I'm not sure if we should say anything about it. Once we have the backend system with the point above, we can also accept array_like inputs that support AD. However, as soon as you go into compiled code that breaks down - AD requires a separate kernel (or even backwards and forwards kernels) per operation. It doesn't really make sense to do that for all of SciPy.

**Comment by stefanv** [comment]
The word `gpu` occurs once in the `scipy.fft` source code.  It looks like the system is based on uarray, which was not discussed in the [original proposal](https://docs.google.com/document/d/1hGMc6ZrsmSi_LSixI5oFbo5cZkPUo92sfmnVthg1u6Y/edit#heading=h.g5yhg5y7vfpo), so I'm not sure where most of this discussion happened (perhaps on the mailing list, I didn't see it pass by but could easily have missed it); the implementation seems to be from [this PR](https://github.com/scipy/scipy/pull/10383).  If this work is still underway, then I hope some documentation is also being developed, because I could not find any in the source repo.

Either way, can this confidently be considered *the* approach for future-proofing SciPy?  It means we have to re-implement all the algorithms we want to run on various backends, whereas there are solutions out there such as numba, pypi, etc. where you can write it once and potentially get some gains (perhaps not optimal) from multiple platforms.

I think SciPy is fundamentally different from NumPy: it cannot easily be reduced to a simple API; a lot of the value is in the detail of the algorithmic implementation.

**Comment by grlee77** [comment]
On Thu, Sep 5, 2019 at 8:05 PM Stefan van der Walt <notifications@github.com>
wrote:

> The word gpu occurs once in the scipy.fft source code. It looks like the
> system is based on uarray, which was not discussed in the original
> proposal
> <https://docs.google.com/document/d/1hGMc6ZrsmSi_LSixI5oFbo5cZkPUo92sfmnVthg1u6Y/edit#heading=h.g5yhg5y7vfpo>,
> so I'm not sure where most of this discussion happened (perhaps on the
> mailing list, I didn't see it pass by but could easily have missed it); the
> implementation seems to be from this PR
> <https://github.com/scipy/scipy/pull/10383>. If this work is still
> underway, then I hope some documentation is also being developed, because I
> could not find any in the source repo.
>
The lack of any mention of gpu is mainly because there is nothing
GPU-specific in SciPy itself. There is an open PR at CuPy (
https://github.com/cupy/cupy/pull/2355) that implements a CUDA-based
backend for scipy.fft, but as that has not yet been merged or released, it
is perhaps premature to create a user-facing demo illustrating its use. The
only 3rd party backend that has been merged is for pyFFTW (
https://github.com/pyFFTW/pyFFTW/pull/269).

Some uarray discussion happened on the mailing list in the following
thread: https://mail.python.org/pipermail/scipy-dev/2019-June/023547.html.
Eric, Ralf, Peter and I decided it seemed like a good fit for the fft
module and I don't think there were any objections from others at the time.
To what extent this approach can extend to other modules will depend on the
availability of alternative implementations that could be used as a near
drop-in replacement. For the FFT case, there were already pyFFTW, mkl-fft
and CuPy that provide similar functionality and API making the creation of
backends for them fairly low effort.

**Comment by rgommers** [comment]
> Either way, can this confidently be considered the approach for future-proofing SciPy?

It's _an_ approach that seems to work well for `fft`. It'll be interesting to see how people fare with this once 1.4.0 gets released. So far there's few alternative approaches; it's clear by now that `__array_ufunc/function__` won't be enough by itself as a general override approach for SciPy, and  I'm not aware of many other actively developed library for this kind of thing (if we need more flexibility than `uarray` provides, [metadsl](https://github.com/quansight-labs/metadsl) may come in handy - then you're talking DAGs, lazy evaluation, etc.). 

> It means we have to re-implement all the algorithms we want to run on various backends, whereas there are solutions out there such as numba, pypi, etc. where you can write it once and potentially get some gains (perhaps not optimal) from multiple platforms.

That's not really true. Also in Numba you have to reimplement every function. Basically, the hard work is writing a GPU or distributed implementation of an algorithm. Once you have that, the rest is interfacing (which is what the uarray-based backend system does). PyPy doesn't run on GPUs at all, so is not relevant here.

> I think SciPy is fundamentally different from NumPy: it cannot easily be reduced to a simple API; a lot of the value is in the detail of the algorithmic implementation.

That's true, but there's a bunch of things to consider:

- All pure Python code (e.g. large parts of `stats`) simply work if you plug in a `numpy.ndarray`-compatible GPU or distributed array
- `special` already has partial implementations in CuPy (GPU, https://github.com/cupy/cupy/blob/master/docs/source/reference/special.rst) and Numba (CPU-only, https://github.com/numba/numba-scipy/tree/master/numba_scipy/special)
- Same for `linalg` which has partial support in Dask: https://github.com/dask/dask/blob/master/dask/array/linalg.py
- This will grow whenever people implement stuff like this for their own needs (or with a concerted push). Either way, all we should aim to do in SciPy is provide a way to override the API.
- The question isn't really limited to SciPy; parts of SciPy are interesting (`linalg`, `fft`, `special`, `optimize` are the first that come to mind), other parts are not; Pandas and Scikit-learn are in a similar boat. This is where things like [RAPIDS](https://docs.rapids.ai/api) (and Arrow, XND, dask-ml, etc.) come in.

> so I'm not sure where most of this discussion happened (perhaps on the mailing list, I didn't see it pass by but could easily have missed it

At the start of the project on the mailing list: https://mail.python.org/pipermail/scipy-dev/2019-May/023506.html. And also on GitHub of course.

**Comment by andyfaff** [comment]
These discussions are interesting from a roadmap POV, so that we have a good idea of where we're heading. However, they may be a little beside the point for a paper. A paper is typically expounding on what one has done, not what one is going to do.

**Comment by grlee77** [comment]
For the purposes of the paper, I think Ralf's statement "all we should aim to do in SciPy is provide a way to override the API" is relevant. There are no concrete plans to include GPU-specific code in SciPy itself, but SciPy provides a reference implementation and API that downstream libraries for GPU, distributed computing etc. can model their own implementations on. It is much easier to develop new code when there is an existing implementation to test against and model the API on. This has already happened for a subset of SciPy in CuPy and things like the recent scipy.fft can serve as a model of how we can make that experience better for downstream libraries.

Is the paper restricted purely to describing the software at the time of the 1.0 release? If so, then disregard mentioning the (not yet released) scipy.fft module or uarray, but I think the broader point still stands.

**Comment by rgommers** [comment]
> Is the paper restricted purely to describing the software at the time of the 1.0 release?

Yes, that's what we aimed for. Also, we limited authorship to contributors up to 1.0, and should have a 2.0 (or 1.Y.0) paper at some point for contributors post-1.0

Agree with not mentioning `scipy.fft`, except for in the reply to reviewers perhaps, and just explaining the principle.

**Comment by stefanv** [comment]
I guess my hope was that we would find ways of supporting several operations out-of-the-box on a wider set of platforms, by using ideas such as gputools or compilers *like* Numba. My concern remains that reimplementing many parts of SciPy is all but trivial, and that encouraging people to override its API may bring more headaches than benefits. I understand that there are also risks in not doing so: monkey (dis)patch is not pretty---but at least then *we're* not making any promises. There's also a question of whether SciPy is the right level on which to build this kind of infrastructure, and whether we want to be making such strong promises about our API stability. All answerable, but will require some thought and discussion. 

But OK, we are agreed that for the paper we can write something fairly generic that describes *some* potential plan---it's not like we will be forced to execute on that vision in the future.

**Comment by rgommers** [comment]
This `gputools`: https://github.com/maweigert/gputools? That seems to be some custom OpenCL kernels + Python code.

> I guess my hope was that we would find ways of supporting several operations out-of-the-box on a wider set of platforms, by using ideas such as gputools or compilers like Numba.

This may interest you: https://pythoncapi.readthedocs.io/pyhandle.html (for easier retargeting of compiled code that uses the Python C API)

**Comment by tylerjereddy** [comment]
It may be worth mentioning that we do now have a concrete example of "backend swapping" where GPUs (etc.) may be used. I'd probably even just briefly mention the `scipy.fft` stuff explicitly (coming in a future release..), deferring any further details to a future paper & note in the rebuttal that we even have some new core developers onboard with expertise in this domain of providing backend flexibility. 

The fact that it is already happening in our master branch is a pretty strong point IMO--discrete steps are being taken so we don't get left behind even if the final / perfect solution may evolve.

In any case, as long as we make a solid effort to address the comment both in the body of the text & in the rebuttal, without "pushing back," the Editors can "check the list" & we should be ok!

**Comment by mdhaber** [comment]
With zero GPU or distributed computing experience, I thought I'd leave a PR to someone else, but I can point out two places in the paper that we might think about addressing this.

First, we might consider adjusting the wording of:
> In terms of software systems and architecture, SciPy's scope matches NumPy's:
algorithms for in-memory computing on single machines, with support for a wide
range of data types and process architectures. Distributed computing and support
for graphics processing units (GPUs) are explicitly out of scope.

I'd actually suggest we remove that last sentence from here and move this discussion to the end of the paragraph about the roadmap:

> Nevertheless, SciPy continually strives to improve.
The SciPy Roadmap\cite{SciPy_roadmap_1,SciPy_roadmap_dev}, summarized in Table~\ref{table:roadmap}, is a
continually updated document
maintained by the community that describes some of the major directions for
improvement for the project, as well as specific limitations and matters that
require assistance moving forward.

Perhaps something better/more accurate than "As distributed memory and GPU computing are increasingly common, SciPy's intentions in these spaces are particularly important to its continued relevance: although specialized algorithms are currently out of scope, we seek for SciPy code to support alternative back-ends (e.g. Dask, CuPy arrays) where possible."
would do the trick.
