### ISSUE TITLE
Editorial Revision: Word Limit Refactor

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#257]
From *Nature Methods* Editorial Team (emphasis mine):

> Our standard word limit is 3000 words for the Introduction, Results and Discussion. We appreciate that shortening to this length is impossible, but we do ask that you try to **trim to below 6000 words**. Based on the formatting in your paper, it might make sense to have **some sections, like Package Organization, as a separate Box**. This would take that part out of the word count and allow you to keep the current formatting. **I think figure 1 should also be its own Box (Box 1) because it is all text.**

**Comment by mdhaber** [comment]
Assuming tables don't count, I'm getting ~7300 words including captions, ~7000 without. We're not going to cut out 1000+ words in <1 week without removing large swaths of content (which we already did to the Background section). Converting the "Package Organization" section to a Box would remove about 800 words. Beyond that, I'll try to remove a few words , mostly from Key technical improvements. 

Converting to boxes needs to be done directly in Word, presumably.

Should I work on removing other words from the LaTeX file, or should we do this in the Word document, too? I'd suggest removing from the Word document, because I don't know that we want content removed from our arXiv revision.

**Comment by tylerjereddy** [comment]
Maybe just in Word unfortunately--that's what I started doing with Word docs updated in Stefan's PR

**Comment by mdhaber** [comment]
Do you know how to create a "Box"? Do you think this means a "text box"?

**Comment by tylerjereddy** [comment]
I think Boxes are indeed just "text boxes" in Word. The first *Nature Methods* PDF I found when I went to their website was a review article with at least four boxes: 
[NMETH_sample.pdf](https://github.com/scipy/scipy-articles/files/3672082/NMETH_sample.pdf)


They are all interspersed throughout the text--they seem to like doing that & they don't look any fancier than normal text boxes in Word.

**Comment by mdhaber** [comment]
OK, but based on the guidelines I don't think we're supposed to attempt to format that. They are now actually requiring us to take figures, tables, (etc... including boxes) out of the text and put them at the bottom.

**Comment by mdhaber** [comment]
Based on those guidelines, it appears that captions do not count against us either, so MS Word says we're at 6239 words.

**Comment by mdhaber** [comment]
@tylerjereddy I was thinking about your suggestion of moving the quotes from the background to a box. I don't think the entire section - with both quotes and intermediate text - can be moved, but I don't see why we can't move Jim Hugunin's quote. Like SciPy 0.1 announcement, we want to include it because it's an important part of the history, but it can be summed up very succinctly in the main text. Then main text could read like:

> In 1995, Jim Hugunin, a graduate student from MIT, wrote the first message17 (Box X) in a new Python Matrix Special Interest Group (Matrix-SIG) mailing list calling for a standardized matrix object. Over the next several months, conversations on that mailing list...

That would save ~70 words. 

Maybe even easier would be to move paragraphs 2-4 of "Language choices" into a box. Then the relevant section of the main text could read like:

> The distribution of secondary programming languages in SciPy is a compromise between a powerful, performance-enhancing language that interacts well with Python (i.e. Cython) and the usage of languages (and their libraries) that have proven reliable and performant over many decades (Box Y).

Should we ask Rita by email, or should we mention in the editorial formatting response letter:
> If additional reductions to the main text are required, we can quickly move paragraphs 2-4 (200 words) of the Language Choices section to a box. The first message in the Matrix-SIG mailing list (70 words) could also be moved to a box if required.

**Comment by tylerjereddy** [comment]
I think we just leave it as is for now as you suggest before. I've never seen a rebuttal letter for Editorial requests but doesn't hurt I guess.

**Comment by mdhaber** [comment]
One of the documents said we needed a point by point response.
