### ISSUE TITLE
Editorial Revision: Reference Count

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#259]
From *Nature Methods* Editorial Team:

> As a guideline, Articles/Brief Communications allow up to 50 references in the main text. Please shorten if possible.

As a side note from Tyler: shifting important but non-critical refs to i.e., SI can often be a problem with providing credit because SI refs don't get accounted for in citation indexing.

**Comment by mdhaber** [comment]
I don't think we have included references inappropriately; I think that we simply cover a lot of ground. This is a review paper of almost 20 years of work, which is pretty different than a typical research article.  We can take another pass, but I don't think it is possible to get it down to 50 without removing a substantial amount of content, and if this is truly a "guideline" rather than strict requirement, I don't think we should shift references to the S.I. just to reduce the number.

**Comment by tylerjereddy** [comment]
Closing because overruled by our Editorial Contact:

> You can keep your references. I agree 50 is not possible in this case.
