### ISSUE TITLE
Editorial Revision: Renumbering Figures after Adding Boxes

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#261]
Since #257 likely means we'll need to add some "Boxes," from *Nature Methods* Editorial Team (emphasis mine):

>  All figures and tables, including Supplementary items, must be cited in the text in numerical order. **Please renumber figures after you’ve made any additional Boxes and be sure to call out each Box in order**.

**Comment by mdhaber** [comment]
Key Technical Improvements -> cKDTree has: 
> This generally improved performance on any given problem (Figure 2) while preserving the asymptotic complexity.

This refers to Figure 2 quite a bit above where we have always had the figure appear (Benchmarking). I'm concerned that if we reference the figure here, it will be placed here by the editors (because we are supposed to submit without embedding figures anywhere). Shall I remove this reference?

**Comment by mdhaber** [comment]
I went ahead and made this change. I think all figures, tables, and boxes are referred to in the text and numbered in the order the references appear.
