### ISSUE TITLE
Using reST, LaTeX or Overleaf? 

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#6]
There were 5 votes for plain LaTeX on the coordination committee, one +0 for reST, @stefanv suggested reST as used in the SciPy conference proceedings on the mailing list. Overleaf can be used by people on top of a git repo with LaTeX, however none of the people who responded particularly liked it - can revisit that later.

**Comment by rgommers** [comment]
Suggestions for code listings were `minted` (by @ev-br) or `listings` (by @ilayn).

**Comment by charris** [comment]
Is there a good reason *not* to use LaTeX?

**Comment by stefanv** [comment]
We use restructured text for the SciPy proceedings to make the reviews easier and more readable.  But since everyone here is comfortable with LaTeX, it's probably fine.

Overleaf is handy when multiple people are co-editing overlapping parts of a document.  That can be addressed with proper coordination (i.e. restricting most of a single user's edits to one section of the paper).

**Comment by WarrenWeckesser** [comment]
It sounds like a decision has been made: LaTeX it is (+1 from me, by the way).  So can this issue be closed?

**Comment by rgommers** [comment]
Agreed, LaTeX it is, closing
